export const leaderboardZh = {
  sectionTitle: "Probing Memes 排行榜",
  bannerTitle: "选择指标、筛选条件，并点击表头箭头进行排序。",
  memeScoreSelect: "选择 Meme Scores",
  memePatternHint:
    "行为模式：指模型群体在题目上的对/错模式。例如，一组题目上所有非推理模型都答错，而推理模型答对；或者所有 Qwen family 模型都答错而其他模型答对。",
  filters: "筛选条件",
  datasetSingle: "数据集（单选）",
  reasoningModes: "推理模式",
  reasoningModesHintLine1: "Base（直接回答）：不显式要求模型展示推理过程；",
  reasoningModesHintLine2: "Chain-of-Thought（CoT）：引导模型生成显式中间推理；",
  reasoningModesHintLine3: "Intrinsic Reasoning（IR）：启用模型内在推理能力（深度思考）。",
  vendors: "厂商",
  selectAll: "全选",
  clear: "清空",
  show: "显示",
  hide: "隐藏",
  modelComparison: "模型对比",
  pick1st: "选择第一个",
  pick2nd: "选择第二个",
  clearComparison: "清空对比",
  compareHint:
    "请选择两个模型：点击任意模型右侧的 vs. 按钮，第一个会高亮；再点击第二个即可生成对比面板。",
  leaderboardBarPrefix: "Leaderboard",
  leaderboardBarSortHint: "排序：点击表头右侧 ▲/▼",
  population: "模型群体",
  dataset: "数据集",
  models: "模型数",
  search: "搜索",
  searchPlaceholder: "输入模型名称…",
  searchAria: "搜索模型",
  searchClearTitle: "清空搜索",
  showing: "当前显示",
  loading: "加载中...",
  sortedBy: "当前排序",
  rank: "排名",
  model: "模型",
  noData: "暂无数据",
  radarComparison: "雷达图对比",
  metricBars: "指标条形图",
  sortLabel: "排序",
  sortAscending: "升序排序",
  sortDescending: "降序排序",
  clickToToggleMetric: "点击切换该指标",
  compareAriaPrefix: "对比",
  compareVsTooltip: "vs.：选择模型进行对比（选中 2 个模型后，会显示对比面板）",
  comparedWith: "相较于",
  accuracyLabel: "Accuracy",
  modeSummary: "推理模式",
  vendorSummary: "厂商",
} as const;